- name: Get Oxid install directory
  stat: path={{ oxid_root }}
  register: oxidDir

- name: Install Oxid via oxrun cli
  tags: oxid
  command: "oxrun install:shop
    --oxidVersion={{ oxid_version }} --installationFolder={{ oxid_root }} --shopURL={{ oxid_config.shop_url }}
    --dbHost={{ oxid_config.db_host }} --dbUser={{ oxid_config.db_user }} --dbPwd={{ oxid_config.db_pass }}
    --adminUser={{ oxid_config.admin_email }} --adminPassword={{ oxid_config.admin_pass }}"
  when: oxidDir.stat.isdir is not defined or not oxidDir.stat.isdir